version: 2

sources:
  - name: raw
    description: "Raw source tables for the magical commerce universe."
    schema: raw_v2_raw
    tables:
      - name: wizards
        description: "Basic wizard attributes."
        columns:
          - name: id
            description: "Primary key."
            tests:
              - not_null
              - unique
      - name: worlds
        description: "All known worlds."
        columns:
          - name: id
            description: "World ID."
            tests:
              - not_null
              - unique
      - name: wand_orders
        description: "Orders placed by wizards."
        columns:
          - name: id
            tests: [not_null, unique]
          - name: wizard_id
            tests: [not_null]
          - name: wand_id
            tests: [not_null]
      - name: wands
        description: "Magical wands."
        columns:
          - name: id
            tests: [not_null, unique]
