name: example
config-version: 2

profile: default

models:
  example:
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
  +persist_docs:
    relation: true
    columns: true
