tutorial:
  target: ci
  outputs:
    ci:
      type: postgres
      host: "{{ env_var('PGHOST') }}"
      port: "{{ env_var('PGPORT') | as_number }}"
      user: "{{ env_var('PGUSER') }}"
      password: "{{ env_var('PGPASSWORD') }}"
      dbname: "{{ env_var('PGDATABASE') }}"
      schema: "{{ env_var('DBT_SCHEMA', 'sao_tutorial') }}"
      threads: 4
