name: example_v2
config-version: 2

profile: default

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

models:
  example_v2:
    staging:
      +materialized: view
    marts:
      +materialized: table
  +persist_docs:
    relation: true
    columns: true

seeds:
  example_v2:
    +schema: raw
