MAX_SEED_SIZE_BYTES = 100 * 1024 * 1024  # 100 MB
ORCHESTRA_REUSED_NODE = "ORCHESTRA_REUSED_NODE"
SERVICE_NAME = "orchestra-dbt"
RESOURCE_TYPES_TO_LS = ["model", "snapshot", "seed"]
VALID_ORCHESTRA_ENVS = ["app", "stage", "dev"]
