version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: src_orders
        config:
          freshness:
            warn_after: { count: 24, period: hour }
          loaded_at_field: order_date
      - name: src_customers
      - name: src_tickets
        config:
          freshness:
            warn_after: { count: 24, period: hour }
          loaded_at_query: "SELECT MAX(ticket_date) FROM {{ this }} WHERE valid = true"

models:
  - name: stg_orders
    description: "Cleaned and standardized orders data"
    columns:
      - name: order_id
        description: "Order ID per order hello world v2!"
        tests:
          - not_null
          - unique
    config:
      tags:
        - a

  - name: stg_customers
    description: "Cleaned and standardized customers data"
    config:
      freshness:
        build_after:
          count: 3
          period: minute
      tags:
        - b

  - name: int_orders
    description: "Intermediate orders table for further aggregations"
    config:
      tags:
        - a
    tests:
      - dbt_utils.expression_is_true:
          arguments:
            expression: "order_id IS NOT NULL"
          config:
            warn_if: "= 0"
            error_if: "> 100"
            severity: warn

  - name: cust_orders
    description: "Final mart combining customers and their orders"
    config:
      freshness:
        build_after:
          count: 3
          period: minute
          updates_on: all
      tags:
        - a
        - b

  - name: dim_customers
    description: "Dimension table for customers"
    config:
      tags:
        - b
