version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: src_orders
        config:
          freshness:
            warn_after: { count: 24, period: hour }
          loaded_at_field: order_date
      - name: src_customers
      - name: src_tickets
        config:
          freshness:
            warn_after: { count: 24, period: hour }
          loaded_at_query: "SELECT MAX(ticket_date) FROM {{ this }} WHERE valid = true"

models:
  - name: stg_orders
    description: "Cleaned and standardized orders data"
    columns:
      - name: order_id
        description: "Order ID per order hello world v2!"
        tests:
          - not_null
          - unique

  - name: stg_customers
    description: "Cleaned and standardized customers data"
    config:
      freshness:
        build_after:
          count: 1
          period: hour

  - name: int_orders
    description: "Intermediate orders table for further aggregations"

  - name: cust_orders
    description: "Final mart combining customers and their orders"
    config:
      freshness:
        build_after:
          count: 1
          period: hour
          updates_on: all

  - name: dim_customers
    description: "Dimension table for customers"
